### ISSUE TITLE
min_video module defect

### ISSUE THREAD

**Issue by ghost** [Wolfyxon/MinVideo#6]
Whenever you specify a Bigger file, or -1 -1, the file width and height will have a number magnitudes bigger than the originally inputted height and Width.
This breaks every player and editing/tool such as @Wolfyxon JS Player, and Python Player, or @Cracko298's MinVideo Tools.
It's fixable by editing the Int64 value in HxD to the actual dimensions based on the docs, but it's not very Userfriendly when a Memory Error happens and no context is given other than Memory Error.
![image](https://github.com/Wolfyxon/MinVideo/assets/131509058/7520fd35-28e0-4cfc-b90f-b8a5b078cb7a)
![image](https://github.com/Wolfyxon/MinVideo/assets/131509058/e9e3f5e7-bfa5-4395-a7fc-0a8b0571b374)

**Comment by Wolfyxon** [comment]
I added minimum size for the JS and Python version that won't allow negative numbers.
Negative numbers cause a bitflip when dealing with pure bytes which makes the numbers way bigger than they should be.

> Whenever you specify a Bigger file,

I tested MinVideo with 200mb files and it worked fine, are you able to provide more info?

**Comment by ghost** [comment]
When using the `cli.py` and `min_video.py`, and the arg `-1 -1` on  a mp4 file.
The demensions as shown above completely screw themselves up.

**Comment by Wolfyxon** [comment]
That should be fixed now, since negative size is not accepted anymore and will result in a error.
